#!/bin/bash

# Quick Jenkins Setup Script for Impact LMS Deployment

echo "=== Jenkins Setup for Impact LMS Deployment ==="
echo ""

echo "1. JENKINS CREDENTIALS SETUP"
echo "   Go to Jenkins → Manage Jenkins → Manage Credentials"
echo "   Add the following credential:"
echo ""
echo "   Type: Secret text"
echo "   ID: server-ssh-password"
echo "   Secret: CStp4DR@2025#"
echo "   Description: SSH password for deployment server (82.25.109.1)"
echo ""

echo "2. JENKINS PIPELINE JOB SETUP"
echo "   - Create new Pipeline job named 'impact-lms-deployment'"
echo "   - Set Pipeline definition to 'Pipeline script from SCM'"
echo "   - Configure your Git repository URL"
echo "   - Set Script Path to 'Jenkinsfile'"
echo ""

echo "3. REQUIRED JENKINS PLUGINS"
echo "   Install these plugins if not already installed:"
echo "   - Pipeline"
echo "   - Git"
echo "   - Docker Pipeline"
echo "   - SSH Agent"
echo "   - Credentials Binding"
echo ""

echo "4. JENKINS SYSTEM REQUIREMENTS"
echo "   - Docker installed on Jenkins server"
echo "   - Network access to deployment server (82.25.109.1)"
echo "   - Sufficient disk space for Docker images"
echo ""

echo "5. DEPLOYMENT FLOW"
echo "   The pipeline will:"
echo "   ✅ Checkout code from Git"
echo "   ✅ Build Docker images for frontend and backend"
echo "   ✅ Run automated tests"
echo "   ✅ Perform security scans"
echo "   ✅ Deploy to server (82.25.109.1)"
echo "   ✅ Run health checks"
echo "   ✅ Setup monitoring"
echo ""

echo "6. SERVER PREPARATION"
echo "   The deployment will automatically:"
echo "   ✅ Install Docker and Docker Compose"
echo "   ✅ Configure firewall (UFW)"
echo "   ✅ Setup application in /opt/impact-lms"
echo "   ✅ Configure monitoring and logging"
echo ""

echo "7. POST-DEPLOYMENT ACCESS"
echo "   Application will be available at:"
echo "   🌐 Frontend: http://82.25.109.1/"
echo "   🔧 API: http://82.25.109.1/api/"
echo "   📊 Health Check: http://82.25.109.1/api/health"
echo ""

echo "8. MONITORING AND LOGS"
echo "   📁 Application logs: docker-compose logs"
echo "   📁 Deployment logs: /var/log/impact-lms-deployment.log"
echo "   📁 Monitoring: /usr/local/bin/impact-lms-monitor.sh"
echo ""

echo "9. SECURITY NOTES"
echo "   ⚠️  Change default passwords in .env.production"
echo "   ⚠️  Configure SSL certificates for HTTPS (recommended)"
echo "   ⚠️  Regular security updates and backups"
echo ""

echo "10. FIRST DEPLOYMENT"
echo "    After Jenkins setup, trigger the first build:"
echo "    - Go to Jenkins job → Build Now"
echo "    - Monitor the console output"
echo "    - Check application accessibility after deployment"
echo ""

echo "=== Setup Complete! ==="
echo "For detailed instructions, see JENKINS_SETUP.md"