#!/bin/bash

# Quick Jenkins Setup Script for Impact LMS Deployment
# Repository: https://github.com/krishnaprasadnr702119/impact-new.git
# Local Jenkins Server Configuration

echo "=== Jenkins Setup for Impact LMS Deployment ==="
echo ""

echo "📍 REPOSITORY INFORMATION"
echo "   GitHub Repository: https://github.com/krishnaprasadnr702119/impact-new.git"
echo "   Target Server: 82.25.109.1"
echo "   Jenkins: Local Server"
echo ""

echo "1. JENKINS JOB SETUP (Local Jenkins)"
echo "   - Open your local Jenkins: http://localhost:8080"
echo "   - Create new Pipeline job named 'impact-lms-deployment'"
echo "   - Pipeline Configuration:"
echo "     • Definition: Pipeline script from SCM"
echo "     • SCM: Git"
echo "     • Repository URL: https://github.com/krishnaprasadnr702119/impact-new.git"
echo "     • Credentials: Add GitHub credentials if private repo"
echo "     • Branch: */main (or your default branch)"
echo "     • Script Path: Jenkinsfile"
echo ""

echo "2. NO CREDENTIALS NEEDED (Password in Pipeline)"
echo "   ✅ Server password (CStp4DR@2025#) is configured in pipeline"
echo "   ✅ No additional Jenkins credentials required"
echo "   ⚠️  Consider using Jenkins credentials for better security"
echo ""

echo "3. REQUIRED JENKINS PLUGINS"
echo "   Install these plugins in your local Jenkins:"
echo "   - Pipeline"
echo "   - Git"
echo "   - Docker Pipeline"
echo "   - GitHub Integration"
echo ""

echo "4. LOCAL JENKINS REQUIREMENTS"
echo "   ✅ Docker installed on Jenkins server"
echo "   ✅ Network access to deployment server (82.25.109.1)"
echo "   ✅ Sufficient disk space for Docker images"
echo "   ✅ sshpass package (will be auto-installed)"
echo ""

echo "5. DEPLOYMENT FLOW"
echo "   The pipeline will:"
echo "   ✅ Checkout code from Git"
echo "   ✅ Build Docker images for frontend and backend"
echo "   ✅ Run automated tests"
echo "   ✅ Perform security scans"
echo "   ✅ Deploy to server (82.25.109.1)"
echo "   ✅ Run health checks"
echo "   ✅ Setup monitoring"
echo ""

echo "6. SERVER PREPARATION"
echo "   The deployment will automatically:"
echo "   ✅ Install Docker and Docker Compose"
echo "   ✅ Configure firewall (UFW)"
echo "   ✅ Setup application in /opt/impact-lms"
echo "   ✅ Configure monitoring and logging"
echo ""

echo "7. POST-DEPLOYMENT ACCESS"
echo "   Application will be available at:"
echo "   🌐 Frontend: http://82.25.109.1/"
echo "   🔧 API: http://82.25.109.1/api/"
echo "   📊 Health Check: http://82.25.109.1/api/health"
echo ""

echo "8. MONITORING AND LOGS"
echo "   📁 Application logs: docker-compose logs"
echo "   📁 Deployment logs: /var/log/impact-lms-deployment.log"
echo "   📁 Monitoring: /usr/local/bin/impact-lms-monitor.sh"
echo ""

echo "9. SECURITY NOTES"
echo "   ⚠️  Change default passwords in .env.production"
echo "   ⚠️  Configure SSL certificates for HTTPS (recommended)"
echo "   ⚠️  Regular security updates and backups"
echo ""

echo "10. FIRST DEPLOYMENT"
echo "    After Jenkins setup, trigger the first build:"
echo "    - Go to Jenkins job → Build Now"
echo "    - Monitor the console output"
echo "    - Check application accessibility after deployment"
echo ""

echo "=== Setup Complete! ==="
echo "For detailed instructions, see JENKINS_SETUP.md"